# Generated by Django 2.2.19 on 2022-06-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
